Repository street62/airbnb, pull requests merged in 2022-05, with the labels that each got.

#2 Build : 초기 환경 세팅, 필요한 라이브러리 설치
  fe/.eslintrc.js
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/tsconfig.json
Labels: environment

#7 Build: 스타일링 환경 세팅
  fe/.eslintrc.js
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/images/FE_숙소예약서비스/Property 1=check.svg
  fe/src/images/FE_숙소예약서비스/Property 1=chevron-left.svg
  fe/src/images/FE_숙소예약서비스/Property 1=chevron-right.svg
  fe/src/images/FE_숙소예약서비스/Property 1=heart.svg
  fe/src/images/FE_숙소예약서비스/Property 1=menu.svg
  fe/src/images/FE_숙소예약서비스/Property 1=minus-circle.svg
  fe/src/images/FE_숙소예약서비스/Property 1=pause-circle.svg
  fe/src/images/FE_숙소예약서비스/Property 1=plus-circle.svg
  fe/src/images/FE_숙소예약서비스/Property 1=search.svg
  fe/src/images/FE_숙소예약서비스/Property 1=star.svg
  fe/src/images/FE_숙소예약서비스/Property 1=user.svg
  fe/src/images/FE_숙소예약서비스/Property 1=x-circle.svg
  fe/src/images/FE_숙소예약서비스/hero-img.svg
  fe/src/images/FE_숙소예약서비스/minus.svg
  fe/src/images/FE_숙소예약서비스/plus.svg
  fe/src/index.css
  fe/src/styles/GlobalStyles.jsx
  fe/src/styles/theme.js
  fe/tsconfig.json
Labels: environment, FE

#9 라우터 지정
  fe/.eslintrc.js
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/Router.tsx
  fe/src/index.tsx
  fe/src/pages/Home.jsx
  fe/src/pages/Layout.jsx
  fe/src/pages/Result.jsx
Labels: router

#11 컨트롤러 레이어 초기 구현
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
Labels: ⚙️BE, ✨feature

#14 검색 결과 조회 Service 로직 구현
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ✨feature

#17 숙소 도메인 구현
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ✨feature

#21 검색 요청 DTO 추가 및 쿼리 파리미터 DTO 매핑
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE

#24 리팩토링
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/PeopleConstraint.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ♻️refactor

#27 Accommodation 위도/경도 필드 수정
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
Labels: ⚙️BE, ♻️refactor

#30 리뷰어님의 코멘트 반영
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
Labels: ⚙️BE, ✨feature, ♻️refactor

#32 Feat: 전체 숙소의 가격 반환하는 API 구현
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ✨feature

#33 [FE] result페이지 UI 구현
  fe/src/components/Header/MiniSearchBar/index.tsx
  fe/src/components/Header/SearchBar/Period.tsx
  fe/src/components/Header/SearchBar/Personnel.tsx
  fe/src/components/Header/SearchBar/Price.tsx
  fe/src/components/Header/SearchBar/index.tsx
  fe/src/components/Header/SearchBar/searchBar.styled.js
  fe/src/components/Header/index.tsx
  fe/src/components/HotelList/Hotel.tsx
  fe/src/components/HotelList/index.tsx
  fe/src/components/Map/index.tsx
  fe/src/components/Modals/PersonnelModal.tsx
  fe/src/components/Skeleton/Hotel.tsx
  fe/src/pages/Result.jsx
Labels: 🌈FE, 🎨 UI

#36 도메인 관련 클래스 JPA 엔티티로 수정 및 새로운 엔티티 추가
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/DiscountPolicy.java
  be/src/main/java/kr/codesquad/airbnb/domain/PeopleConstraint.java
  be/src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  be/src/main/java/kr/codesquad/airbnb/domain/User.java
Labels: ⚙️BE, ✨feature

#46 Dto, 레포지토리, 엔티티 관련 수정
  be/src/main/java/kr/codesquad/airbnb/domain/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/Member.java
  be/src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
Labels: ⚙️BE, ♻️refactor

#51 숙소 예약 페이지 GET API 구현
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ✨feature

#54 [BE] 숙소 예약 페이지 POST API 구현
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/Reservation.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
  be/src/main/java/kr/codesquad/airbnb/repository/MemberRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/ReservationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ✨feature

#55 [BE] 숙소 예약 페이지 GET API 수정
  be/src/main/java/kr/codesquad/airbnb/domain/DiscountPolicy.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
Labels: ⚙️BE, 🔨fix

#57 [BE] 코드 리팩토링
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/domain/accommodation/Accommodation.java
  be/src/main/java/kr/codesquad/airbnb/domain/accommodation/AccommodationNotFoundException.java
  be/src/main/java/kr/codesquad/airbnb/domain/discountpolicy/DiscountPolicy.java
  be/src/main/java/kr/codesquad/airbnb/domain/member/Member.java
  be/src/main/java/kr/codesquad/airbnb/domain/member/MemberNotFoundException.java
  be/src/main/java/kr/codesquad/airbnb/domain/reservation/Reservation.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveFormResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
  be/src/main/java/kr/codesquad/airbnb/exception/CustomException.java
  be/src/main/java/kr/codesquad/airbnb/exception/CustomExceptionHandler.java
  be/src/main/java/kr/codesquad/airbnb/exception/ErrorResponse.java
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/MemberRepository.java
  be/src/main/java/kr/codesquad/airbnb/repository/ReservationRepository.java
  be/src/main/java/kr/codesquad/airbnb/service/AccommodationService.java
Labels: ⚙️BE, ♻️refactor

#60 AccommodationController의 RegisterReservation() 반환타입 변경 및 ReserveRequestDto의 날짜 매핑 어노테이션 추가
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/dto/ReserveRequestDto.java
Labels: ⚙️BE, 🔨fix

#62 모달 on/off와 관련된 기능 구현
  fe/src/components/Header/SearchBar/Period.tsx
  fe/src/components/Header/SearchBar/Personnel.tsx
  fe/src/components/Header/SearchBar/Price.tsx
  fe/src/components/Header/SearchBar/SearchButton.tsx
  fe/src/components/Header/SearchBar/index.tsx
  fe/src/components/Header/SearchBar/searchBar.styled.ts
  fe/src/components/Modals/PeriodModal.tsx
  fe/src/components/Modals/PersonnelModal.tsx
  fe/src/components/Modals/PriceModal.tsx
  fe/src/contexts/ModalContext.tsx
  fe/src/pages/Layout.jsx
Labels: 🌈FE

#63 [BE] 숙소 검색 쿼리 수정
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
Labels: ⚙️BE, 🔨fix
