Repository street62/airbnb, pull requests merged in 2022-06, with the labels that each got.

#81 [BE] 테이블 이름 소문자로 통일하게 수정
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
  be/src/main/resources/dml.sql
Labels: ⚙️BE, 🔨fix

#82 [BE] MySQL 의존성 추가 및 배포용 스프링 프로필 추가
  be/build.gradle
  be/src/main/resources/application.yml
  be/src/main/resources/logback-spring.xml
Labels: ⚙️BE

#83 [BE] AWS 배포 환경 구축
  .github/workflows/prod-deploy-be.yml
  be/Dockerfile
  be/appspec.yml
  be/scripts/deploy.sh
Labels: ⚙️BE

#89 [BE] CORS 문제 해결 및 숙소 검색 결과 반환 API 수정
  be/src/main/java/kr/codesquad/airbnb/controller/AccommodationController.java
  be/src/main/java/kr/codesquad/airbnb/dto/SearchQueryResponseDto.java
Labels: ⚙️BE, 🔨fix

#92 [BE] 토큰 검증 로직 스프링 인터셉터를 활용한 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/airbnb/AirbnbApplication.java
  be/src/main/java/kr/codesquad/airbnb/configuration/FilterConfig.java
  be/src/main/java/kr/codesquad/airbnb/configuration/JwtConfig.java
  be/src/main/java/kr/codesquad/airbnb/filter/LoginValidateFilter.java
  be/src/main/java/kr/codesquad/airbnb/token/TokenProvider.java
  be/src/main/resources/application.yml
Labels: ⚙️BE, ✨feature

#95 [FE] 필터에 해당하는 숙소 렌더링, 지도 마커 띄우기, 지도 드래그 활성화, 지도 줌인아웃 구현
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/components/Header/SearchBar/Personnel.tsx
  fe/src/components/Header/SearchBar/SearchButton.tsx
  fe/src/components/HotelList/Filter.tsx
  fe/src/components/HotelList/Hotel.tsx
  fe/src/components/HotelList/index.tsx
  fe/src/components/Map/index.tsx
  fe/src/hooks/useFetch.tsx
  fe/src/utils/util.tsx
Labels: 🌈FE, ✨feature

#96 Fix: 한 숙소 내의 예약이 여러 건일 때 숙소 검색 시 중복되는 문제 수정
  be/src/main/java/kr/codesquad/airbnb/repository/AccommodationRepository.java
Labels: bug, ⚙️BE, 🔨fix
